name=Arduino_Video
version=1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Video library for Arduino boards
paragraph=
category=Display
url=https://github.com/arduino-libraries/Arduino_Video
architectures=mbed,mbed_portenta,mbed_giga,ArduinoCore-zephyr
