name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # libraries to install for all boards
      UNIVERSAL_LIBRARIES: |
        - source-path: ./
        - name: ArduinoGraphics
        - name: lvgl
        - name: Arduino_GigaDisplayTouch
      # sketch paths to compile (recursive) for all boards
      UNIVERSAL_SKETCH_PATHS: |
        - examples/ArduinoLogo
        - examples/ArduinoLogoDrawing
        - examples/LVGLDemo

      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: "arduino:zephyr_main:giga"
            platform-name: arduino:zephyr_main
            artifact-name-suffix: arduino-zephyr_main-giga
          - fqbn: "arduino:zephyr_main:portentah7"
            platform-name: arduino:zephyr_main
            artifact-name-suffix: arduino-zephyr_main-portentah7

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            ${{ env.UNIVERSAL_LIBRARIES }}
            ${{ matrix.libraries }}
          sketch-paths: |
            ${{ env.UNIVERSAL_SKETCH_PATHS }}
            ${{ matrix.sketch-paths }}
          enable-deltas-report: "true"
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
